name: Continuous Integration

on:
  push:
    branches: [main]
    paths-ignore:
      - "**.gitignore"
      - "**.md"
  pull_request:
    branches: [main]
    paths-ignore:
      - "**.gitignore"
      - "**.md"

jobs:
  test:
    name: Lint, test, coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          # Py 3.7 is current default Py3 version on an RPi
          python-version: 3.7
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm 
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
      - name: Install NodeJS dependencies
        run: npm ci
      - name: Install Python dependencies
        run: pip3 install coverage flake8 opencv-python-headless
      - name: Build (Transpile TypeScript)
        # Unless code coverage is 100%, tests (using ts-node, a runtime
        # interpretation engine) can not guarantee untouched code is not broken.
        # Transpile the TypeScript to ensure it is all at least valid TypeScript.
        run: npm run transpile
      # Test
      - name: Lint and test
        run: npm run test:ci
      - name: Upload coverage to Code-Climate
        uses: paambaati/codeclimate-action@v2.6.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: echo "Coverage already calculated - skipping calculating coverage"
          coverageLocations: |
            ${{github.workspace}}/coverage/typescript/lcov.info:lcov
            ${{github.workspace}}/coverage/python/coverage.xml:coverage.py
      # Artifacts
      - name: Upload coverage report artifact
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage
